enum MAIN_STACK_NAVIGATOR {
  HOME_TAB_NAVIGATOR = 'HOME_TAB_NAVIGATOR',
}

enum AUTH_STACK_NAVIGATOR {
  LOGIN_SCREEN = 'LOGIN_SCREEN',
  HOME = 'HOME',
}

enum HOME_TAB_NAVIGATOR {
  HOME = 'HOME',
}
export {MAIN_STACK_NAVIGATOR, AUTH_STACK_NAVIGATOR, HOME_TAB_NAVIGATOR};
